-- no solution

-- Consider all integer combinations of a^(b) for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
-- 
    -- 2^(2)=4, 2^(3)=8, 2^(4)=16, 2^(5)=32
    -- 3^(2)=9, 3^(3)=27, 3^(4)=81, 3^(5)=243
    -- 4^(2)=16, 4^(3)=64, 4^(4)=256, 4^(5)=1024
    -- 5^(2)=25, 5^(3)=125, 5^(4)=625, 5^(5)=3125
-- 
-- If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
-- 
-- 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
-- 
-- How many distinct terms are in the sequence generated by a^(b) for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

require "euler"

function T(a, b)
  local m = b-1
  local r = a*a
  local q = b
  print(a, q, m, r)
  while r <= b do
    q = math.floor((q+1)/2) - 1
    m = m - q - 1
    print(a, q, m, r)
    r = r*a
  end
  -- print(a, m, r)
  print(m)
  return m
end

function T2(a, b)
  if a==1 then return 1 end
  local r = math.sqrt(a)
  s = a .. ": "
  if math.floor(r)==r then
    -- for i = 2, b, 2 do
      -- s = s .. " " .. math.pow(a, i+math.floor((b+1)/2)-2)
    -- end
    -- print(s)
    return math.floor((b+1)/2)
  else
    -- for i = 2, b do
      -- s = s .. " " .. math.pow(a, i)
    -- end
    -- print(s)
    return b-1
  end
end

m = 0
X = 10
for i= 2, X do
  m = m + T(i, X)
end
print(m)
